### CREATE USERS 
POST http://localhost:6789/api/v1/users/register HTTP/1.1
content-type: application/json

{
    "name": "kenneth",
    "email": "kenneth@gmail.com",
    "password": "1234"
}

### login USERS 
POST http://localhost:6789/api/v1/users/login HTTP/1.1
content-type: application/json

{
     "email": "kenneth@gmail.com",
    "password": "1234"
}

### all USERS 
GET http://localhost:6789/api/v1/users/all HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzA4Mjc5MzMsImV4cCI6MTczMDgyOTczM30.hcl5xqTFIdrY_Ubs88HtOesvpjKgnrI7otZdmDqagJc

### single USER
GET http://localhost:6789/api/v1/users/b4b639d0-7015-468a-8cb3-dac7715fea2f HTTP/1.1
content-type: application/json

### myprofile USER
GET http://localhost:6789/api/v1/users/myprofile HTTP/1.1
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0YjYzOWQwLTcwMTUtNDY4YS04Y2IzLWRhYzc3MTVmZWEyZiIsImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJpYXQiOjE3MzAxNDY3NDcsImV4cCI6MTczMDE0ODU0N30.zMU3lGrh_B6p9Zb3TLv5pD1BNWxhl_6vBqNvGiJhRBA


### create categories  
POST http://localhost:6789/api/v1/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAzOTk0NzIsImV4cCI6MTczMDQwMTI3Mn0.Vr4BX6XYtX8UUSB7wa8zm2zTYbAqy-byRkB5lvXASh8

{
    "title": "category 2",
    "description": "Like cat.... 2"
}

### single category 
GET http://localhost:6789/api/v1/categories/a88ad80c-4e69-4f55-89f6-b1ab6a080f55 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM

### ALL categoRIES
GET http://localhost:6789/api/v1/categories HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM

### update categories  
PATCH http://localhost:6789/api/v1/categories/a88ad80c-4e69-4f55-89f6-b1ab6a080f55 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM

{
    "title": "category 1 modify",
    "description": "Like cat.... modified"
}

### CREATE products 
POST http://localhost:6789/api/v1/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzExNTQwMTYsImV4cCI6MTczMTE1NTgxNn0.vnVTq0mkM2kh9-dBAjUjN3RPE_gYdKrGO9cPPkw-smk

{
    "title": "prod 8",
    "description": "Wdesc 8......",
    "price": 470.00,
    "stock": 61,
    "images": ["img1","img2","img3"],
    "categoryId": "2dd50c9d-9d05-4a8d-b357-6a863b56feb0"
}

### update products 
PATCH http://localhost:6789/api/v1/products/76e494ce-a7fb-41fb-a0d7-ce8aa3bd39c7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzA0MDIxNzgsImV4cCI6MTczMDQwMzk3OH0.eVYZIlNV2PFV7MJL9Uzx7mWdXKymiNOa_MtgmInIclI

{
    "title": "prod 2222",
    "description": "Wdesc 22222 ......",
    "price": 260.00,
    "stock": 14,
    "images": ["img1","img2","img3"],
    "categoryId": "e2d64258-f28d-426f-af7b-08acfb6fad35"
}

### ALL products
GET http://localhost:6789/api/v1/products HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM

### single product
GET http://localhost:6789/api/v1/products/76e494ce-a7fb-41fb-a0d7-ce8aa3bd39c7 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM

### delete product
DELETE http://localhost:6789/api/v1/products/f286807f-5381-46ac-be78-263da2c9608a HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM


### CREATE reviews 
POST http://localhost:6789/api/v1/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2MzViNjRhLWQ0ZTgtNGVhMC05YmYwLTA0ZmVmYTJlNDgzNiIsImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJpYXQiOjE3MzExNTM3MzAsImV4cCI6MTczMTE1NTUzMH0.1RrO6QUOtA_z0j1rWraH4jLkwnU27NKbRQCcdz6Toeg

{
    "productId": "76e494ce-a7fb-41fb-a0d7-ce8aa3bd39c7",
    "rating": 4,
    "comment": "the product is good"
}

### single review
GET http://localhost:6789/api/v1/reviews/719af172-32fe-48ba-9564-f8a8ad61f82c HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOGM2NzQ5LTAwYzEtNGQ4My05ODhlLWFlNWM1NzUyNTUwZCIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzAyMzIzMDIsImV4cCI6MTczMDIzNDEwMn0.AD0XnTL7pHPAF1o1ph5DVUFqspX_Qq8Po9yFihzAMdM


### delete single review
DELETE http://localhost:6789/api/v1/reviews/719af172-32fe-48ba-9564-f8a8ad61f82c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzA5MTM2MjQsImV4cCI6MTczMDkxNTQyNH0.WXkoqlxMbLrpWBQ5MPLlf0IHvuhdqQ1szJL4AHmwkO4


### all reviews for a perticular product
GET http://localhost:6789/api/v1/reviews/719af172-32fe-48ba-9564-f8a8ad61f82c HTTP/1.1
Content-Type: application/json



### CREATE ORDERS 
POST http://localhost:6789/api/v1/orders HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2MzViNjRhLWQ0ZTgtNGVhMC05YmYwLTA0ZmVmYTJlNDgzNiIsImVtYWlsIjoibGFsYUBnbWFpbC5jb20iLCJpYXQiOjE3MzExNDM1OTcsImV4cCI6MTczMTE0NTM5N30.0PazCMIVVav4cjtvpqkYO_iVwSuj2Riv_r6OOb2-92w

{
    "shippedAddress": {
        "name": "Andrew Stewart",
        "phone": "+2349098787654",
        "address": "123 Main St",
        "city": "Anytown",
        "postCode": "12345",
        "state": "CA",
        "country": "USA"
    },
    "orderedProducts":[{
        "id": "76e494ce-a7fb-41fb-a0d7-ce8aa3bd39c7",
        "product_unit_price": 260.00,
        "product_quantity": 4
    },
    {
          "id": "fe1c67bd-3e69-4ac2-b410-8ede634126f8",
        "product_unit_price": 260.00,
        "product_quantity": 16
    }]
}

### single order
GET http://localhost:6789/api/v1/orders/719af172-32fe-48ba-9564-f8a8ad61f82c HTTP/1.1
Content-Type: application/json

### all orders
GET http://localhost:6789/api/v1/orders HTTP/1.1
Content-Type: application/json

### update orders status
PUT http://localhost:6789/api/v1/orders/0176d6a4-b303-4c06-93a3-7a83aa7558f2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzExNDk2MzAsImV4cCI6MTczMTE1MTQzMH0.DPzKugUwqG7uQK9pfhuVNWAGkgIP42JK0IIrStsbRvw

{
    "status": "delivered"
}

### cancel orders
PUT http://localhost:6789/api/v1/orders/cancel/0176d6a4-b303-4c06-93a3-7a83aa7558f2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3MzY1YWY1LTY1OWEtNDAxZC1hMTZiLWY5NDEyZjRhZTk0MiIsImVtYWlsIjoia2VubmV0aEBnbWFpbC5jb20iLCJpYXQiOjE3MzExNDk2MzAsImV4cCI6MTczMTE1MTQzMH0.DPzKugUwqG7uQK9pfhuVNWAGkgIP42JK0IIrStsbRvw

{
    "status": "cancelled"
}